# docker/docker-compose.yml
version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: imdb_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../sql/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_net

volumes:
  pgdata:

networks:
  app_net:
    driver: bridge
